/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 * Karnveer Ubhi
 * Activity 1 
 * November 10, 2020
 */
public class Activity1 extends javax.swing.JFrame {
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity1().setVisible(true);
            }
        });   
    }
    /**
     * Creates new form FrameActivity1
     */
    public Activity1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblWords = new javax.swing.JLabel();
        lblDefintions = new javax.swing.JLabel();
        lblWord1 = new javax.swing.JLabel();
        lblWord2 = new javax.swing.JLabel();
        lblWord3 = new javax.swing.JLabel();
        lblWord4 = new javax.swing.JLabel();
        lblWord5 = new javax.swing.JLabel();
        lblDefintions1 = new javax.swing.JLabel();
        lblDefintions2 = new javax.swing.JLabel();
        lblDefintions3 = new javax.swing.JLabel();
        lblDefintions4 = new javax.swing.JLabel();
        lblDefintions5 = new javax.swing.JLabel();
        txtInput1 = new javax.swing.JTextField();
        txtInput2 = new javax.swing.JTextField();
        txtInput3 = new javax.swing.JTextField();
        txtInput4 = new javax.swing.JTextField();
        txtInput5 = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnNextpage = new javax.swing.JButton();
        lblHelp = new javax.swing.JLabel();
        txtTermInput = new javax.swing.JTextField();
        lblOutput = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitle.setText("Activity 1: Matching Defintions (Enter number of defitions to corresponding word)");

        lblWords.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblWords.setText("Terms");

        lblDefintions.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblDefintions.setText("Defintions");

        lblWord1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWord1.setText("1. Mental Disorder");

        lblWord2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWord2.setText("2. Depression");

        lblWord3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWord3.setText("3. Schizophrenia");

        lblWord4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWord4.setText("4. Medication");

        lblWord5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWord5.setText("5. Psychotherapy ");

        lblDefintions1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDefintions1.setText("1. Shown through sadness, low self-esteem, loss of interest in activities");

        lblDefintions2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDefintions2.setText("2. Used in order to treat patients based on what mental disorder the patient has");

        lblDefintions3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDefintions3.setText("3. A therapy which teaches the patient how to deal with their problems and  strategies to deal with certain situations.");

        lblDefintions4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDefintions4.setText("4. A condition that affects your thinking, feelings, mood, and behavior");

        lblDefintions5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDefintions5.setText("5. Causes hallucinations, illusions, and disorganized speech and behaviour.");

        btnExit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCheck.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnNextpage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnNextpage.setText("Next Page");
        btnNextpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextpageActionPerformed(evt);
            }
        });

        lblHelp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHelp.setText("Help:  Enter 1 number of  a term above  for free defintion (No Words,  Numbers between 1 - 5). ");

        txtTermInput.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblScore.setText("Score:");

        btnPrevious.setText("Previous Page");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWord1)
                                    .addComponent(btnCheck))
                                .addGap(26, 26, 26)
                                .addComponent(lblIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblWord5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDefintions1)
                                    .addComponent(lblDefintions4)
                                    .addComponent(lblDefintions5)
                                    .addComponent(lblDefintions2)
                                    .addComponent(lblDefintions3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtTermInput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblWord2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblWord3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblWord4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInput4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInput5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(lblWords)
                                        .addGap(337, 337, 337)
                                        .addComponent(lblDefintions)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious)
                .addGap(12, 12, 12)
                .addComponent(btnNextpage)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExit)
                        .addComponent(btnNextpage))
                    .addComponent(btnPrevious))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWords, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDefintions))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWord1)
                    .addComponent(lblDefintions1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWord2)
                    .addComponent(lblDefintions2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWord3)
                    .addComponent(lblDefintions3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWord4)
                    .addComponent(lblDefintions4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWord5)
                    .addComponent(lblDefintions5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck)
                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTermInput)
                    .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
       
    // Variables that are used in the method 
    int counter1 = 0;
    int answer1, answer2, answer3, answer4, answer5;
    String Incorrect = "The following terms are incorrect: ";
    
    /* Try-Catch used for error handling which executes the following code which takes all the input values from the user and checks if they
    are the right answer if it is increases the score by 1 and if not adds that term to the incorrect variable. After, it outputs the score and any terms 
    that you have matched incorrectly. Finally, it checks for any errors and if they are displays a message that will help the user fix it. */
    
    try {
        answer1 = (Integer.parseInt(txtInput1.getText()));
        answer2 = (Integer.parseInt(txtInput2.getText()));
        answer3 = (Integer.parseInt(txtInput3.getText()));
        answer4 = (Integer.parseInt(txtInput4.getText()));
        answer5 = (Integer.parseInt(txtInput5.getText()));
        if (answer1 == 4){
             counter1++;
         } else {
             Incorrect += " Term 1";
        }
        if (answer2 == 1){
             counter1++;
         } else {
             Incorrect += " Term 2";
        }
        if (answer3 == 5){
             counter1++;
         } else {
             Incorrect += " Term 3";
        }
        if (answer4 == 2){
             counter1++;
         } else {
             Incorrect += " Term 4";
        }
        if (answer5 == 3){
             counter1++;
         } else {
             Incorrect += " Term 5";
        }
        
        lblScore.setText("Score: " + counter1 + "/5");
        lblIncorrect.setText(Incorrect);   
    
        } catch(Exception e){       
        lblIncorrect.setText("Invalid input. Please make sure input values are integers and boxes have been filled");
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        // Closes the program
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        
        // makes Section3 frame visible and this frame invisible
        new Section3().setVisible(true);
        this.setVisible(false); 
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextpageActionPerformed
        
        // Makes Activity2 frame visible and this frame invisible
        new secondActivity().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnNextpageActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed

        //creates an arraylsit to store all data from textfile.
        ArrayList <String> txtFile = new ArrayList <String>();

        /* Code to read each line of text in the Terms file, and than adds it to an unlimated arraylist storing both numbers
        and names of the books. */
        BufferedReader br = null;

        try {
            br = new BufferedReader(new FileReader("Terms.txt"));
            String word;
            while ((word = br.readLine()) != null ){
                txtFile.add(word);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        /* Converts the arraylist to a array to use in methods by changing its size match the arraylists and then transfering
        all the index values. */
        String [] txtFile2 = new String[txtFile.size()];
        txtFile.toArray(txtFile2);

        // Creates new integer arraylisst for reference numbers only
        ArrayList <Integer> termnumber = new ArrayList <Integer>();

        /* For loop that goes through every index value in original arraylist, than checks if the index is dividble by 2 and
        leaves a remander of 0 as every even index number represents a number of a defintion which is than stored in a
        sepereate array. */
        for (int i = 0; i < txtFile2.length; i++) {
            if (i % 2 == 0) {
                termnumber.add(Integer.parseInt(txtFile2[i]));
            }
        }

        /* Converts the arraylist filled with term numbers to a normal array by setting its size the same as the
        arraylists, than converts all the index values in the arraylist to the array. */
        Integer [] termnumber2 = new Integer[termnumber.size()];
        termnumber.toArray(termnumber2);

        // Creates new arraylist to store booktitles only
        ArrayList <String> Defintion = new ArrayList <String>();

        /* For loop statement that goes through every index value in the terms arraylist, then checks if the remander of i
        divided by 2 is not 0 because we know every even index value is a termnumber not a defintion. If the statement is
        true it adds the defintion to the defintion arraylist. */
        for (int i = 0; i < txtFile2.length; i++) {
            if (i % 2 != 0) {
                Defintion.add(txtFile2[i]);
            }
        }

        /* Converts the Defintion arraylist to a normal array by setting its size the same as the arraylists, than transfering
        all the index values from the arraylist into the array. */
        String [] Defintion2 = new String[Defintion.size()];
        Defintion.toArray(Defintion2);

        int counter = 1;
        int Binary = -1;

        try {
            counter--;
            int number = (Integer.parseInt(txtTermInput.getText()));
            Binary = TermSearch(termnumber2, number, 0, termnumber2.length);
            if(Binary >= 0 || counter == 0){
                lblOutput.setText(Defintion2[Binary]);
                btnHelp.setVisible(false);
            } else
            lblOutput.setText("The number was not found in our library.");
        } catch(Exception e){
            lblOutput.setText("Invalid input. Please make sure input boxes are integers and have been filled");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHelpActionPerformed

    //Search Array Method
    public static int TermSearch(Integer[] num, int target, int start,  int end){
        
        // Decalres and intiliazes the variables needed in the method
        int middle;
        
        // If then that checks if there are no more numbers to check then if not return that none were found
        if (start > end){
            return -1;
        }
        
        // Adds the start and end and than divides them by 2 to get the middle
        middle = (start + end)/2;   
        
        /* If then statement that checks if the middle number is equal to the target which is the value inputed by the user. If
        it is returns the middle value */
        if(num[middle] == target){
            return middle;
        }
        
        /* If then statement that checks if the number is not found than checks the left instead or than will check the right
        side instead */
        if (num[middle] < target){
            return TermSearch(num, target, middle+1, end);   
        }
            return TermSearch(num, target, start, middle-1);
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNextpage;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDefintions;
    private javax.swing.JLabel lblDefintions1;
    private javax.swing.JLabel lblDefintions2;
    private javax.swing.JLabel lblDefintions3;
    private javax.swing.JLabel lblDefintions4;
    private javax.swing.JLabel lblDefintions5;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWord1;
    private javax.swing.JLabel lblWord2;
    private javax.swing.JLabel lblWord3;
    private javax.swing.JLabel lblWord4;
    private javax.swing.JLabel lblWord5;
    private javax.swing.JLabel lblWords;
    private javax.swing.JTextField txtInput1;
    private javax.swing.JTextField txtInput2;
    private javax.swing.JTextField txtInput3;
    private javax.swing.JTextField txtInput4;
    private javax.swing.JTextField txtInput5;
    private javax.swing.JTextField txtTermInput;
    // End of variables declaration//GEN-END:variables
}
